defaults:
  - _self_
  - data: graph_datamodule/default  # Fixed the path format
  - model: ml_coarsening
  - callbacks: default
  - logger: mlflow  # For experiment tracking
  - trainer: default
  - paths: default

train: True
# Training-specific parameters
seed: 42

