run_name: ${generate_run_name:}

defaults:
  - _self_
  - data: train_default  # Fixed the path format
  - model: ml_coarsening
  - callbacks: default
  - logger: mlflow  # For experiment tracking
  - trainer: default
  - paths: default
  - debug: null
  - hydra: default
  - experiment: null

train: True
test: True
task_name: "train"
ckpt_path: null
# Training-specific parameters
seed: 42

